### Numpy : Linear Algebra Library for Python

## Installing

Choose one of the following commands:

`conda install numpy`

`pip install numpy`

In [2]:
import numpy as np
np.version.version

'1.15.4'

## Numpy Arrays

### Vectors

In [ ]:
list = [1,2,3,4]
np_arr = np.array(list)
np_arr

### Matrices

In [ ]:
# Criando 2D
mat1 = [[1,2,3],[2,4,8],[3,9,27]]
np_arr2 = np.array(mat1)
np_arr2

In [ ]:
list_of_lists = [[1,2,3],[2,4,8],[3,9,27]]
np_mat = np.array(list_of_lists)
np_mat

In [ ]:
np_arr2

### Utility functions

#### np.arange

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(10, 22, 2)

array([10, 12, 14, 16, 18, 20])

In [5]:
np.arange(20, 0, -2)

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

## Special matrices

#### np.eye, np.zeros, np.ones

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((4,3))

In [ ]:
np.ones(3)

In [ ]:
np.ones((4,3))

#### np.linspace

In [8]:
with_linspace = np.linspace(0, 10, 100)
print('Size:', with_linspace.size)
with_linspace

Size: 100


array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [ ]:
with_arange = np.arange(0, 10.1, 0.1)
print('Size:', with_arange.size)
with_arange

In [ ]:
with_linspace = np.linspace(0, 10, 101)
print(with_linspace.size)
with_linspace

## Generating random data

### Integer

In [ ]:
np.random.randint(1, 21)

In [ ]:
np.random.randint(1, 21, 5)

In [9]:
np.random.randint(1, 21, 5, dtype='i')

array([15,  3, 12,  5,  3], dtype=int32)

In [10]:
np.random.randint(1, 21, 5, dtype='f')

TypeError: Unsupported dtype "float32" for randint

In [15]:
np.random.randint(1, 21, 5).astype("float")

array([11., 13.,  2., 15., 10.])

#### Uniform distribution

In [11]:
np.random.rand(3)

array([0.48049197, 0.86371903, 0.32673538])

In [13]:
np.random.rand(2, 3)

TypeError: rand() got an unexpected keyword argument 'dtype'

#### Normal distribution

In [16]:
np.random.randn(2, 2)

array([[-1.63432546,  0.70079336],
       [ 1.43561841,  1.34803019]])

## Working with np.array

### max(), min(), mean()

In [ ]:
l = np.random.randint(1,100,10)
print(l)
print("Max: {} | Min: {} | Average: {}".format(l.max(), l.min(), l.mean()))

In [ ]:
print("Max value is {} and its index is {}.".format(l.max(), l.argmax()))
print("Min value is {} and its index is {}.".format(l.min(), l.argmin()))

### Dimensions and data types

In [ ]:
v = np.random.randint(0, 100, 50)
v

In [ ]:
v.shape

In [ ]:
v = v.reshape(5, 10)
v

In [ ]:
v.shape

In [ ]:
v.dtype

In [ ]:
v = v.astype('f')
v.dtype

In [ ]:
v

### Selection with np.array

#### Selection in vectors

In [19]:
p = np.arange(1,21)
p

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
p[2]

In [ ]:
p[0:3] 

In [ ]:
p[:3] 

In [ ]:
p[3:]

In [ ]:
p[0:18]

In [ ]:
p[:-2]

#### Selection in matrices

In [20]:
m = p.reshape(4, 5)
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
m[0]

In [23]:
m[0, :]

array([1, 2, 3, 4, 5])

In [22]:
m[:, 1]

array([ 2,  7, 12, 17])

In [21]:
m[:][1] #Wrong!

array([ 6,  7,  8,  9, 10])

In [ ]:
m[0][0]

In [ ]:
m[0:2, 0:3]

#### Conditional selection

In [ ]:
c = np.arange(1,10)
c

In [ ]:
bool_sel = c > 5

In [ ]:
c[bool_sel]

In [ ]:
c[c < 5]

#### np.select()

In [ ]:
s = np.arange(1, 10)
cond_list = [s < 3, s > 5]
choice_list = [s, s**2]
np.select(cond_list, choice_list)

### Broadcast and Copy

In [25]:
x = np.arange(1, 21)
y = x[0:5] 
y

array([1, 2, 3, 4, 5])

In [26]:
y[0:5] = 30
y

array([30, 30, 30, 30, 30])

In [27]:
x

array([30, 30, 30, 30, 30,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [28]:
z = np.arange(1,21)
w = z.copy()[0:5]
w[0:5] = 30
w

array([30, 30, 30, 30, 30])

In [29]:
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

## Numpy operations

In [ ]:
f = np.arange(0, 5)
g = np.arange(5, 10)
h = f + g
print("{} + {} = {}".format(f, g, h))

In [ ]:
i = g - f
print("{} - {} = {}".format(g, f, i))

In [ ]:
j = f * g
print("{} * {} = {}".format(f, g, j))

In [ ]:
k = f ** g
print("{} ** {} = {}".format(f, g, k))

In [ ]:
l = f / g
print("{} / {} = {}".format(f, g, l))

In [ ]:
print("{} + {} = {}".format(f, 2, f + 2))
print("{} - {} = {}".format(f, 2, f - 2))
print("{} * {} = {}".format(f, 2, f * 2))
print("{} ** {} = {}".format(f, 2, f ** 2))
print("{} / {} = {}".format(f, 2, f / 2))

In [ ]:
print("{} / {} = {}".format(f, f, f / f))

In [ ]:
print("1 / {} = {}".format(f, 1 / f))

## Universal Functions (https://docs.scipy.org/doc/numpy-1.13.0/reference/ufuncs.html)

In [ ]:
another_matrix = np.arange(1, 13).reshape(3, 4)
print(another_matrix)
maximum = np.max(another_matrix)
minimum = np.min(another_matrix)
average = np.mean(another_matrix)
print("Max = {} | Min = {} | Average = {}".format(maximum, minimum, average))

In [ ]:
col_sum = another_matrix.sum(0)
row_sum = another_matrix.sum(1)
print("col_sum:{} | row_sum:{}".format(col_sum, row_sum))