### Numpy : Linear Algebra Library for Python

## Installing

Choose one of the following commands:

`conda install numpy`

`pip install numpy`

In [1]:
import numpy as np
np.version.version

'1.15.4'

## Numpy Arrays

### Vectors

In [2]:
list = [1,2,3,4]
np_arr = np.array(list)
np_arr

array([1, 2, 3, 4])

### Matrices

In [3]:
# Criando 2D
mat1 = [[1,2,3],[2,4,8],[3,9,27]]
np_arr2 = np.array(mat1)
np_arr2

array([[ 1,  2,  3],
       [ 2,  4,  8],
       [ 3,  9, 27]])

In [4]:
list_of_lists = [[1,2,3],[2,4,8],[3,9,27]]
np_mat = np.array(list_of_lists)
np_mat

array([[ 1,  2,  3],
       [ 2,  4,  8],
       [ 3,  9, 27]])

In [5]:
np_arr2

array([[ 1,  2,  3],
       [ 2,  4,  8],
       [ 3,  9, 27]])

### Utility functions

#### np.arange

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(10, 22, 2)

array([10, 12, 14, 16, 18, 20])

In [8]:
np.arange(20, 0, -2)

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

## Special matrices

#### np.eye, np.zeros, np.ones

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### np.linspace

In [14]:
with_linspace = np.linspace(0, 10, 100)
print('Size:', with_linspace.size)
with_linspace

Size: 100


array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [15]:
with_arange = np.arange(0, 10.1, 0.1)
print('Size:', with_arange.size)
with_arange

Size: 101


array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [16]:
with_linspace = np.linspace(0, 10, 101)
print(with_linspace.size)
with_linspace

101


array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

## Generating random data

### Integer

In [20]:
np.random.randint(1, 21)

7

In [21]:
np.random.randint(1, 21, 5)

array([ 8,  5,  1, 10,  3])

In [22]:
np.random.randint(1, 21, 5, dtype='i')

array([ 4, 12,  6,  8,  5], dtype=int32)

In [23]:
np.random.randint(1, 21, 5, dtype='f')

TypeError: Unsupported dtype "float32" for randint

In [24]:
np.random.randint(1, 21, 5).astype("float")

array([19., 14., 16., 16., 18.])

#### Uniform distribution

In [25]:
np.random.rand(3)

array([0.49203256, 0.75571891, 0.4720009 ])

In [26]:
np.random.rand(2, 3)

array([[0.48551308, 0.22634838, 0.43356526],
       [0.55052731, 0.17194337, 0.02167719]])

#### Normal distribution

In [27]:
np.random.randn(2, 2)

array([[-0.24414018, -0.38228054],
       [ 1.04904624,  0.31898751]])

## Working with np.array

### max(), min(), mean()

In [28]:
l = np.random.randint(1,100,10)
print(l)
print("Max: {} | Min: {} | Average: {}".format(l.max(), l.min(), l.mean()))

[93 87 19 14 64 46 16 62 51 21]
Max: 93 | Min: 14 | Average: 47.3


In [29]:
print("Max value is {} and its index is {}.".format(l.max(), l.argmax()))
print("Min value is {} and its index is {}.".format(l.min(), l.argmin()))

Max value is 93 and its index is 0.
Min value is 14 and its index is 3.


### Dimensions and data types

In [41]:
v = np.random.randint(0, 100, 50)
v

array([22, 52, 63, 72, 95, 14, 83, 37, 58, 64, 18,  8, 25, 56, 48, 83, 17,
       70, 32, 92, 53, 27, 18, 44, 92, 88, 36, 95,  5, 98, 92, 41, 15, 97,
       51, 49, 72, 57, 99, 69,  5, 80, 65,  2, 84, 42, 28, 18, 29, 34])

In [43]:
v = v.reshape(1, 50)
v.shape
v

array([[22, 52, 63, 72, 95, 14, 83, 37, 58, 64, 18,  8, 25, 56, 48, 83,
        17, 70, 32, 92, 53, 27, 18, 44, 92, 88, 36, 95,  5, 98, 92, 41,
        15, 97, 51, 49, 72, 57, 99, 69,  5, 80, 65,  2, 84, 42, 28, 18,
        29, 34]])

In [32]:
v = v.reshape(5, 10)
v

array([[33, 45, 98, 11, 74, 11, 54, 31, 63, 26],
       [92, 40, 80,  3,  9, 27, 57, 38,  9, 53],
       [55,  6, 48, 66, 57, 35, 86, 82, 97, 30],
       [40, 24, 74, 23, 48, 10, 92,  5, 51, 44],
       [21, 13, 93, 10, 38, 30, 25, 50, 36, 12]])

In [33]:
v.shape

(5, 10)

In [34]:
v.dtype

dtype('int64')

In [35]:
v = v.astype('f')
v.dtype

dtype('float32')

In [36]:
v

array([[33., 45., 98., 11., 74., 11., 54., 31., 63., 26.],
       [92., 40., 80.,  3.,  9., 27., 57., 38.,  9., 53.],
       [55.,  6., 48., 66., 57., 35., 86., 82., 97., 30.],
       [40., 24., 74., 23., 48., 10., 92.,  5., 51., 44.],
       [21., 13., 93., 10., 38., 30., 25., 50., 36., 12.]], dtype=float32)

### Selection with np.array

#### Selection in vectors

In [44]:
p = np.arange(1,21)
p

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [45]:
p[2]

3

In [46]:
p[0:3] 

array([1, 2, 3])

In [47]:
p[:3] 

array([1, 2, 3])

In [48]:
p[3:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [49]:
p[0:18]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [50]:
p[:-2]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

#### Selection in matrices

In [51]:
m = p.reshape(4, 5)
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [52]:
m[0]

array([1, 2, 3, 4, 5])

In [53]:
m[0, :]

array([1, 2, 3, 4, 5])

In [54]:
m[:, 1]

array([ 2,  7, 12, 17])

In [55]:
m[:][1] #Wrong!

array([ 6,  7,  8,  9, 10])

In [56]:
m[0][0]

1

In [57]:
m[0:2, 0:3]

array([[1, 2, 3],
       [6, 7, 8]])

#### Conditional selection

In [58]:
c = np.arange(1,10)
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
bool_sel = c > 5
bool_sel

array([False, False, False, False, False,  True,  True,  True,  True])

In [60]:
c[bool_sel]

array([6, 7, 8, 9])

In [62]:
c[c < 5]

array([1, 2, 3, 4])

#### np.select()

In [63]:
s = np.arange(1, 10)
cond_list = [s < 3, s > 5]
choice_list = [s, s**2]
np.select(cond_list, choice_list)

array([ 1,  2,  0,  0,  0, 36, 49, 64, 81])

### Broadcast and Copy

In [64]:
x = np.arange(1, 21)
y = x[0:5] 
y

array([1, 2, 3, 4, 5])

In [65]:
y[0:5] = 30
y

array([30, 30, 30, 30, 30])

In [66]:
x

array([30, 30, 30, 30, 30,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [67]:
z = np.arange(1,21)
w = z.copy()[0:5]
w[0:5] = 30
w

array([30, 30, 30, 30, 30])

In [68]:
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

## Numpy operations

In [69]:
f = np.arange(0, 5)
g = np.arange(5, 10)
h = f + g
print("{} + {} = {}".format(f, g, h))

[0 1 2 3 4] + [5 6 7 8 9] = [ 5  7  9 11 13]


In [70]:
i = g - f
print("{} - {} = {}".format(g, f, i))

[5 6 7 8 9] - [0 1 2 3 4] = [5 5 5 5 5]


In [71]:
j = f * g
print("{} * {} = {}".format(f, g, j))

[0 1 2 3 4] * [5 6 7 8 9] = [ 0  6 14 24 36]


In [72]:
k = f ** g
print("{} ** {} = {}".format(f, g, k))

[0 1 2 3 4] ** [5 6 7 8 9] = [     0      1    128   6561 262144]


In [73]:
l = f / g
print("{} / {} = {}".format(f, g, l))

[0 1 2 3 4] / [5 6 7 8 9] = [0.         0.16666667 0.28571429 0.375      0.44444444]


In [74]:
print("{} + {} = {}".format(f, 2, f + 2))
print("{} - {} = {}".format(f, 2, f - 2))
print("{} * {} = {}".format(f, 2, f * 2))
print("{} ** {} = {}".format(f, 2, f ** 2))
print("{} / {} = {}".format(f, 2, f / 2))

[0 1 2 3 4] + 2 = [2 3 4 5 6]
[0 1 2 3 4] - 2 = [-2 -1  0  1  2]
[0 1 2 3 4] * 2 = [0 2 4 6 8]
[0 1 2 3 4] ** 2 = [ 0  1  4  9 16]
[0 1 2 3 4] / 2 = [0.  0.5 1.  1.5 2. ]


In [75]:
print("{} / {} = {}".format(f, f, f / f))

[0 1 2 3 4] / [0 1 2 3 4] = [nan  1.  1.  1.  1.]


/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [76]:
print("1 / {} = {}".format(f, 1 / f))

1 / [0 1 2 3 4] = [       inf 1.         0.5        0.33333333 0.25      ]


/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


## Universal Functions (https://docs.scipy.org/doc/numpy-1.13.0/reference/ufuncs.html)

In [77]:
another_matrix = np.arange(1, 13).reshape(3, 4)
print(another_matrix)
maximum = np.max(another_matrix)
minimum = np.min(another_matrix)
average = np.mean(another_matrix)
print("Max = {} | Min = {} | Average = {}".format(maximum, minimum, average))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Max = 12 | Min = 1 | Average = 6.5


In [94]:
col_sum = another_matrix.sum(0)
row_sum = another_matrix.sum(1)
test = another_matrix.sum(2)
print("col_sum:{} | row_sum:{}".format(col_sum, row_sum))
test

AxisError: axis 2 is out of bounds for array of dimension 2

In [96]:
threeD = np.arange(27).reshape((3,3,3))
threeD

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [90]:
a = threeD.sum(0)
b = threeD.sum(1)
c = threeD.sum(2)

In [91]:
a

array([[27, 30, 33],
       [36, 39, 42],
       [45, 48, 51]])

In [92]:
b

array([[ 9, 12, 15],
       [36, 39, 42],
       [63, 66, 69]])

In [93]:
c

array([[ 3, 12, 21],
       [30, 39, 48],
       [57, 66, 75]])